INSERT INTO communes
(id,
name,
region)
VALUES
('1','Puente Alto','Metropolitana de Santiago'),
('2','Maipú','Metropolitana de Santiago'),
('3','Santiago','Metropolitana de Santiago'),
('4','La Florida','Metropolitana de Santiago'),
('5','Antofagasta','Antofagasta'),
('6','Viña del Mar','Valparaíso'),
('7','Las Condes','Metropolitana de Santiago'),
('8','San Bernardo','Metropolitana de Santiago'),
('9','Valparaíso','Valparaíso'),
('10','Peñalolén','Metropolitana de Santiago'),
('11','Temuco','La Araucanía'),
('12','Rancagua','Libertador General Bernardo O´Higgins'),
('13','Concepción','Biobío'),
('14','Quilicura','Metropolitana de Santiago'),
('15','Ñuñoa','Metropolitana de Santiago'),
('16','Talca','Maule'),
('17','Pudahuel','Metropolitana de Santiago'),
('18','Coquimbo','Coquimbo'),
('19','Arica','Arica y Parinacota'),
('20','La Serena','Coquimbo'),
('21','Iquique','Tarapacá'),
('22','La Pintana','Metropolitana de Santiago'),
('23','Puerto Montt','Los Lagos'),
('24','Chillán','Ñuble'),
('25','El Bosque','Metropolitana de Santiago'),
('26','Calama','Antofagasta'),
('27','Recoleta','Metropolitana de Santiago'),
('28','Copiapó','Atacama'),
('29','Valdivia','Los Ríos'),
('30','Quilpué','Valparaíso'),
('31','Talcahuano','Biobío'),
('32','Osorno','Los Lagos'),
('33','Renca','Metropolitana de Santiago'),
('34','Los Ángeles','Biobío'),
('35','Providencia','Metropolitana de Santiago'),
('36','Estación Central','Metropolitana de Santiago'),
('37','Cerro Navia','Metropolitana de Santiago'),
('38','San Pedro de la Paz','Biobío'),
('39','Conchalí','Metropolitana de Santiago'),
('40','Curicó','Maule'),
('41','Villa Alemana','Valparaíso'),
('42','Punta Arenas','Magallanes y de la Antártica Chilena'),
('43','La Granja','Metropolitana de Santiago'),
('44','Macul','Metropolitana de Santiago'),
('45','Coronel','Biobío'),
('46','Quinta Normal','Metropolitana de Santiago'),
('47','San Miguel','Metropolitana de Santiago'),
('48','Alto Hospicio','Tarapacá'),
('49','Lo Barnechea','Metropolitana de Santiago'),
('50','Pedro Aguirre Cerda','Metropolitana de Santiago'),
('51','Independencia','Metropolitana de Santiago'),
('52','Lo Espejo','Metropolitana de Santiago'),
('53','Huechuraba','Metropolitana de Santiago'),
('54','Lo Prado','Metropolitana de Santiago'),
('55','San Joaquín','Metropolitana de Santiago'),
('56','La Reina','Metropolitana de Santiago'),
('57','Hualpén','Biobío'),
('58','La Cisterna','Metropolitana de Santiago'),
('59','Colina','Metropolitana de Santiago'),
('60','San Antonio','Valparaíso'),
('61','Chiguayante','Biobío'),
('62','Vitacura','Metropolitana de Santiago'),
('63','Peñaflor','Metropolitana de Santiago'),
('64','San Ramón','Metropolitana de Santiago'),
('65','Cerrillos','Metropolitana de Santiago'),
('66','Ovalle','Coquimbo'),
('67','Linares','Maule'),
('68','Quillota','Valparaíso'),
('69','Melipilla','Metropolitana de Santiago'),
('70','Buin','Metropolitana de Santiago'),
('71','San Felipe','Valparaíso'),
('72','Los Andes','Valparaíso'),
('73','San Fernando','Libertador General Bernardo O´Higgins'),
('74','Talagante','Metropolitana de Santiago'),
('75','Padre Hurtado','Metropolitana de Santiago'),
('76','Coyhaique','Aysén del General Carlos Ibáñez del Campo'),
('77','Machalí','Libertador General Bernardo O´Higgins'),
('78','Angol','La Araucanía'),
('79','La Calera','Valparaíso'),
('80','Penco','Biobío'),
('81','Vallenar','Atacama'),
('82','Lota','Biobío'),
('83','Tomé','Biobío'),
('84','Alerce','Los Lagos'),
('85','Padre Las Casas','La Araucanía'),
('86','Concón','Valparaíso'),
('87','Placilla de Peñuelas','Valparaíso'),
('88','Limache','Valparaíso'),
('89','Rengo','Libertador General Bernardo O´Higgins'),
('90','Lampa','Metropolitana de Santiago'),
('91','Molina','Maule'),
('92','Constitución','Maule'),
('93','Castro','Los Lagos'),
('94','San Carlos','Ñuble'),
('95','Cauquenes','Maule'),
('96','Villarrica','La Araucanía'),
('97','Paine','Metropolitana de Santiago'),
('98','Parral','Maule'),
('99','Culenar','Maule'),
('100','Curanilahue','Biobío'),
('101','El Monte','Metropolitana de Santiago'),
('102','San Javier','Maule'),
('103','Graneros','Libertador General Bernardo O´Higgins'),
('104','Ancud','Los Lagos'),
('105','Chillán Viejo','Ñuble'),
('106','La Unión','Los Ríos'),
('107','Quintero','Valparaíso'),
('108','Puerto Varas','Los Lagos'),
('109','Victoria','La Araucanía'),
('110','Tocopilla','Antofagasta'),
('111','Lautaro','La Araucanía'),
('112','Mulchén','Biobío'),
('113','Labranza','La Araucanía'),
('114','Nacimiento','Biobío'),
('115','Santa Cruz','Libertador General Bernardo O´Higgins'),
('116','Lebu','Biobío'),
('117','San Vicente de Tagua Tagua','Libertador General Bernardo O´Higgins'),
('118','Cartagena','Valparaíso'),
('119','Illapel','Coquimbo'),
('120','San Clemente','Maule'),
('121','Hualqui','Biobío'),
('122','La Cruz','Valparaíso'),
('123','Cañete','Biobío'),
('124','La Ligua','Valparaíso'),
('125','Puerto Natales','Magallanes y de la Antártica Chilena'),
('126','Nueva Imperial','La Araucanía'),
('127','Curacaví','Metropolitana de Santiago'),
('128','Casablanca','Valparaíso'),
('129','Llaillay','Valparaíso'),
('130','Arauco','Biobío'),
('131','Quellón','Los Lagos'),
('132','Pucón','La Araucanía'),
('133','Puerto Aysén','Aysén del General Carlos Ibáñez del Campo'),
('134','Valle Grande','Metropolitana de Santiago'),
('135','Río Bueno','Los Ríos'),
('136','Chimbarongo','Libertador General Bernardo O´Higgins'),
('137','Batuco','Metropolitana de Santiago'),
('138','Pitrufquén','La Araucanía'),
('139','Collipulli','La Araucanía'),
('140','La Laja','Biobío'),
('141','Calbuco','Los Lagos'),
('142','Vicuña','Coquimbo'),
('143','Caldera','Atacama'),
('144','Loncoche','La Araucanía'),
('145','Los Álamos','Biobío'),
('146','Cabrero','Biobío'),
('147','El Quisco','Valparaíso'),
('148','Traiguén','La Araucanía'),
('149','Isla de Maipo','Metropolitana de Santiago'),
('150','Los Vilos','Coquimbo'),
('151','Salamanca','Coquimbo'),
('152','Llanquihue','Los Lagos'),
('153','Frutillar','Los Lagos'),
('154','Mejillones','Antofagasta'),
('155','Pichilemu','Libertador General Bernardo O´Higgins'),
('156','San Francisco de Mostazal','Libertador General Bernardo O´Higgins'),
('157','Purranque','Los Lagos'),
('158','Olmué','Valparaíso'),
('159','Ciudad del Valle','Metropolitana de Santiago'),
('160','La Islita','Metropolitana de Santiago'),
('161','Carahue','La Araucanía'),
('162','Paillaco','Los Ríos'),
('163','Panguipulli','Los Ríos'),
('164','Chañaral','Atacama'),
('165','Bulnes','Ñuble'),
('166','Chicureo','Metropolitana de Santiago'),
('167','Taltal','Antofagasta'),
('168','Cabildo','Valparaíso'),
('169','Yungay','Ñuble'),
('170','Requínoa','Libertador General Bernardo O´Higgins'),
('171','Coelemu','Ñuble'),
('172','San Esteban','Valparaíso'),
('173','Quillón','Ñuble'),
('174','Andacollo','Coquimbo'),
('175','Tierra Amarilla','Atacama'),
('176','El Melón','Valparaíso'),
('177','San José de la Mariquina','Los Ríos'),
('178','Yumbel','Biobío'),
('179','Los Lagos','Los Ríos'),
('180','Calle Larga','Valparaíso'),
('181','Santa Juana','Biobío'),
('182','Teno','Maule'),
('183','Quirihue','Ñuble'),
('184','Hijuelas','Valparaíso'),
('185','Pozo Almonte','Tarapacá'),
('186','Coihueco','Ñuble'),
('187','Algarrobo','Valparaíso'),
('188','Lo Miranda','Libertador General Bernardo O´Higgins'),
('189','Nogales','Valparaíso'),
('190','El Principal','Metropolitana de Santiago'),
('191','Nancagua','Libertador General Bernardo O´Higgins'),
('192','Gorbea','La Araucanía'),
('193','Peumo','Libertador General Bernardo O´Higgins'),
('194','Lanco','Los Ríos'),
('195','Las Ventanas','Valparaíso'),
('196','Villa Alegre','Maule'),
('197','Rinconada','Valparaíso'),
('198','Santa Bárbara','Biobío'),
('199','Los Muermos','Los Lagos'),
('200','Calera de Tango','Metropolitana de Santiago'),
('201','Huépil','Biobío'),
('202','Catemu','Valparaíso'),
('203','Las Cabras','Libertador General Bernardo O´Higgins'),
('204','Chamisero','Metropolitana de Santiago'),
('205','Santa María','Valparaíso'),
('206','Purén','La Araucanía'),
('207','Doñihue','Libertador General Bernardo O´Higgins'),
('208','Fresia','Los Lagos'),
('209','Diego de Almagro','Atacama'),
('210','Quinta de Tilcoco','Libertador General Bernardo O´Higgins'),
('211','Cunco','La Araucanía'),
('212','Hanga Roa','Valparaíso'),
('213','Dalcahue','Los Lagos'),
('214','Longaví','Maule'),
('215','Futrono','Los Ríos'),
('216','Huasco','Atacama'),
('217','Maule','Maule'),
('218','Alto Jahuel','Metropolitana de Santiago'),
('219','La Punta','Libertador General Bernardo O´Higgins'),
('220','El Tabo','Valparaíso'),
('221','Río Negro','Los Lagos'),
('222','Colbún','Maule'),
('223','Putaendo','Valparaíso'),
('224','Codegua','Libertador General Bernardo O´Higgins'),
('225','Monte Águila','Biobío'),
('226','Monte Patria','Coquimbo'),
('227','Renaico','La Araucanía'),
('228','Romeral','Maule'),
('229','Vilcún','La Araucanía'),
('230','San José de Maipo','Metropolitana de Santiago'),
('231','El Palqui','Coquimbo'),
('232','Santo Domingo','Valparaíso'),
('233','Chépica','Libertador General Bernardo O´Higgins'),
('234','Hospital','Metropolitana de Santiago'),
('235','El Salvador','Atacama'),
('236','Porvenir','Magallanes y de la Antártica Chilena'),
('237','Combarbalá','Coquimbo'),
('238','Hualañé','Maule'),
('239','Punitaqui','Coquimbo'),
('240','Cajón','La Araucanía'),
('241','Chonchi','Los Lagos'),
('242','Pichidegua','Libertador General Bernardo O´Higgins'),
('243','Tongoy','Coquimbo'),
('244','Tiltil','Metropolitana de Santiago'),
('245','Rauco','Maule'),
('246','Retiro','Maule'),
('247','Las Cruces','Valparaíso'),
('248','Coltauco','Libertador General Bernardo O´Higgins'),
('249','Freire','La Araucanía'),
('250','Gultro','Libertador General Bernardo O´Higgins'),
('251','San Pedro de Atacama','Antofagasta'),
('252','Bollenar','Metropolitana de Santiago'),
('253','Peralillo','Libertador General Bernardo O´Higgins'),
('254','Puchuncaví','Valparaíso'),
('255','Laraquete','Biobío'),
('256','Chile Chico','Aysén del General Carlos Ibáñez del Campo'),
('257','Cochrane','Aysén del General Carlos Ibáñez del Campo'),
('258','Puerto Williams','Magallanes y de la Antártica Chilena'),
('259','Putre','Arica y Parinacota'),
('260','Chaitén','Los Lagos');